# Generated by Django 2.0.3 on 2018-04-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20180406_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='isbn',
        ),
        migrations.AddField(
            model_name='textbook',
            name='cover_image_URL',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
